### PR TITLE
Replace the std client with gnet client in custom_codec example

### PR DESCRIPTION
**Pull request by wathenjiang**
As [Gnet client is now available for production](https://github.com/panjf2000/gnet/releases), we could use client in gnet instead. 

But I'm not 100% sure I use [client.go](https://github.com/panjf2000/gnet/blob/dev/client.go) correctly, please let me know if there are any mistakes.

### CODE REVIEW

**Comment by panjf2000** [comment]
You provide nothing here and expect me to pick up mistakes?

**Comment by wathenjiang** [comment]
> You provide nothing here and expect me to pick up mistakes?

I means you uesed [smallnest/goframe](https://github.com/smallnest/goframe) to implement a tcp client, but now cloud use client in gnet.

You not yet provided a quite simple client example in gnet.

**Comment by panjf2000** [comment]
Oh sorry, this is a PR, I thought it's an issue.

**Comment by panjf2000** [comment]
Have you tested your new code? Did it work?
@Spongecaptain

**Comment by wathenjiang** [comment]
@panjf2000 I have tested it and it worked well. Turning [smallnest/goframe](https://github.com/smallnest/goframe) to [client.go in gnet](https://github.com/panjf2000/gnet/blob/dev/client.go) just a little bit amendment.

You can find commands by:

- https://github.com/Spongecaptain/gnet-examples/blob/master/examples/codec/client/client.go#L26
- https://github.com/Spongecaptain/gnet-examples/blob/master/examples/codec/server/server.go#L58

&&

- https://github.com/Spongecaptain/gnet-examples/blob/master/examples/custom_codec/client/client.go#L33
- https://github.com/Spongecaptain/gnet-examples/blob/master/examples/custom_codec/server/server.go#L60

**Comment by panjf2000** [comment]
Why is `go.mod` changed so much？ did you run `go mod tidy` before opening this PR? @Spongecaptain

**Comment by wathenjiang** [comment]
> Why is `go.mod` changed so much？ did you run `go mod tidy` before opening this PR? @Spongecaptain 

I did run the go mod tidy.

**Comment by panjf2000** [comment]
Thanks~

**Pull request merged**
